# Generated by Django 6.0.1 on 2026-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_icon', models.CharField(blank=True, default='', max_length=500)),
                ('preferred_color', models.CharField(blank=True, default='', max_length=32)),
                ('images', models.JSONField(blank=True, default=list)),
                ('memory_options', models.JSONField(blank=True, default=list)),
                ('disabled_memory_options', models.JSONField(blank=True, default=list)),
                ('color_options', models.JSONField(blank=True, default=list)),
                ('color_variants', models.JSONField(blank=True, default=dict)),
                ('characteristics', models.JSONField(blank=True, default=list)),
                ('description_text', models.TextField(blank=True, default='')),
                ('terms', models.JSONField(blank=True, default=list)),
                ('description_section', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
