# Generated by Django 6.0.1 on 2026-01-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescriptionCharacteristicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_variants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_section',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disabled_memory_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memory_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preferred_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_icon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/preview/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.SlugField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(default='0', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='products/characteristics/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDescriptionCharacteristicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('value_text', models.CharField(blank=True, default='', max_length=255)),
                ('value_list', models.JSONField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productdescriptioncharacteristicgroup')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDescriptionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_title', models.CharField(blank=True, default='Details', max_length=128)),
                ('details_desc', models.TextField(blank=True, default='')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description_section', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='productdescriptioncharacteristicgroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics_groups', to='products.productdescriptionsection'),
        ),
        migrations.CreateModel(
            name='ProductTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='products/terms/')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_options', to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'hex_value')},
            },
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'color_hex')},
            },
        ),
        migrations.CreateModel(
            name='ProductDisabledMemoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_memory_options', to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductMemoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_options', to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'value')},
            },
        ),
    ]
