# Generated by Django 6.0.1 on 2026-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdescriptioncharacteristicgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcoloroption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcolorvariant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productdescriptioncharacteristicgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productdescriptioncharacteristicitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productdisabledmemoryoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productmemoryoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productterm',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productcoloroption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productcolorvariant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productdisabledmemoryoption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productmemoryoption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productcharacteristic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/icons/'),
        ),
        migrations.AlterField(
            model_name='productcoloroption',
            name='hex_value',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='productcolorvariant',
            name='color_hex',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='productdescriptioncharacteristicgroup',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productdescriptioncharacteristicitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productdescriptionsection',
            name='details_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productdisabledmemoryoption',
            name='value',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='productmemoryoption',
            name='value',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='productterm',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/icons/'),
        ),
        migrations.AlterField(
            model_name='productterm',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
    ]
