# Generated by Django 6.0.1 on 2026-01-27 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcharacteristic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory'),
        ),
    ]
